# Generated by Django 3.2.10 on 2021-12-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredienttype',
            name='measurement_unit',
            field=models.CharField(max_length=20, verbose_name='measurement_unit'),
        ),
        migrations.AlterField(
            model_name='ingredienttype',
            name='title',
            field=models.CharField(max_length=256, verbose_name='имя'),
        ),
        migrations.AddConstraint(
            model_name='favoriterecipes',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique favorite user recipe'),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'author'), name='unique follow'),
        ),
        migrations.AddConstraint(
            model_name='ingredienttype',
            constraint=models.UniqueConstraint(fields=('title', 'measurement_unit'), name='unique ingredient type'),
        ),
        migrations.AddConstraint(
            model_name='recipetag',
            constraint=models.UniqueConstraint(fields=('recipe', 'tag'), name='unique recipe tag'),
        ),
    ]
