# Generated by Django 3.2.10 on 2021-12-11 18:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredient',
            field=models.ManyToManyField(through='recipes.RecipeIngredients', to='recipes.Ingredient'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(default='#42aaff', max_length=7, validators=[django.core.validators.RegexValidator(message='The HEX code is not valid, please use the format #ffffff', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')]),
        ),
    ]
