# Generated by Django 3.2.10 on 2021-12-13 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20211213_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
