# Generated by Django 3.2.10 on 2021-12-10 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_ingredient_unique ingredient'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ingredienttype',
            name='unique ingredient type',
        ),
        migrations.RenameField(
            model_name='ingredienttype',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='ingredienttype',
            constraint=models.UniqueConstraint(fields=('name', 'measurement_unit'), name='unique ingredient type'),
        ),
    ]
