# Generated by Django 3.2.10 on 2021-12-15 19:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211215_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subscriber',
        ),
        migrations.AddField(
            model_name='user',
            name='subscribers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
